module.exports = {
  App_Logo: require("../assets/images/App_Logo.png"),
  BackGroundImgColor: require("../assets/images/BackGraundImgColor.png"),
  App_Logo1: require("../assets/images/App_Logo1.png"),
  Back_Arrow: require("../assets/images/Back_Arrow.png"),
  TermsIcon: require("../assets/images/TermsIcon.png"),
  Menu_Icon: require("../assets/images/Menu_Icon.png"),
  Pick_up: require("../assets/images/Pick_up.png"),
  Threee: require("../assets/images/Threee.png"),
  Tenker: require("../assets/images/Tenker.png"),
  Tata_ace: require("../assets/images/Tata_ace.png"),
  E_V: require("../assets/images/E_V.png"),
  Maps_icon: require("../assets/images/Maps_icon.png"),
  Sucsess_icon: require("../assets/images/Sucsess_icon.png"),
  Phone_icon: require("../assets/images/Phone_icon.png"),
  Profile_image: require("../assets/images/Profile_image.png"),
  Arrow_Roght_icon: require("../assets/images/Arrow_Roght_icon.png"),
  TandC_icon: require("../assets/images/TandC_icon.png"),
  Edit_Icon: require("../assets/images/Edit_Icon.png"),
  Truck_icon: require("../assets/images/Truck_icon.png"),
  delete_user: require("../assets/images/delete_user.png"),
  GoogleMarker: require("../assets/images/GoogleMarker.gif"),
  MarkerGoogle: require("../assets/images/MarkerGoogle.png"),
};
